[workspace]
resolver = "2"

members = [
  "build-tools/build-params-finder",
  "build-tools/script-merge-tool",
  "tests/sphincsplus_rust",
  "tools/ckb-sphincs-tools",
  "tools/ckb-sphincs-utils",
]

[profile.release]
overflow-checks = true
strip = false
codegen-units = 1
debug = true
