[package]
name = "script-merge-tool"
version = "0.1.0"
description = "A helper tool to aid merging multiple binaries together for CKB usage"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["cargo", "derive"] }
glob = "0.3.2"
goblin = "0.9.3"
